#!/bin/bash

# A script to compute the power from a gem5 simulation
# Takes as parameters, the paths to config.ini, stats.txt template.xml, configuration.xml, the parser program and the mcpat program.

# Example
# ./compute stats.txt config.ini template.xml configuration.xml gem5-mcpat-parser/gem5-mcpat-parser mcpat/mcpat

./$5 -s $1 -c $2 -x $3 -o $4
./$6 -infile $4 -print_level 5
